#!/usr/bin/env bash
# The script will display the active TCP and UDP ports on the system
echo "Active Internet connections (only servers)"
sudo netstat -tulnp | awk 'NR==1 || /LISTEN/'

echo
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxp | awk 'NR==1 || /LISTEN/'
