#!/usr/bin/env bash
echo "Active Internet connections (only servers)"
sudo netstat -tulnp | awk 'NR==1 || /LISTEN/'

echo
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxp | awk 'NR==1 || /LISTEN/'
