#!/usr/bin/env bash
# This script changes the IP of the localhost and facebook.com in the /etc/hosts file
sed -i "s/^[^#]*\blocalhost\b.*/127.0.0.1 localhost/" "/etc/hosts"
sed -i "s/^[^#]*\bfacebook.com\b.*/8.8.8.8 facebook.com/" "/etc/hosts"
